# https://taskfile.dev
version: '3'
vars:
  BINFILE: gini

tasks:
  default:
    cmds:
      - task -a

  build:
    cmds:
      - CGO_ENABLED=0 go build .

  lint:
    cmds:
      - golangci-lint run --timeout 5m

  snapshot:
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot
    
  release:
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --skip validate

  godoc:
    cmds:
      - godoc -http=:6060

  tests:
    dir: tests
    cmds:
      - venom run testsuite.yml --output-dir="log" --stop-on-failure
      - venom run delsection.yml --output-dir="log" --stop-on-failure

    